// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_practice.DbContexts;

#nullable disable

namespace api_practice.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250502143947_AddCityAndPoitsOfInterestSeed")]
    partial class AddCityAndPoitsOfInterestSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("api_practice.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The capital of Iran",
                            Name = "Tehran"
                        },
                        new
                        {
                            Id = 2,
                            Description = "City of poets",
                            Name = "Shiraz"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Historic city in northwest Iran",
                            Name = "Tabriz"
                        },
                        new
                        {
                            Id = 4,
                            Description = "is the best city of iran",
                            Name = "Esfahan"
                        });
                });

            modelBuilder.Entity("api_practice.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 4,
                            Description = "The best bridge of Iran",
                            Name = "33 pol"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 4,
                            Description = "the biggest squar in isfahan",
                            Name = "imam squar"
                        });
                });

            modelBuilder.Entity("api_practice.Entities.PointOfInterest", b =>
                {
                    b.HasOne("api_practice.Entities.City", "City")
                        .WithMany("PointOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("api_practice.Entities.City", b =>
                {
                    b.Navigation("PointOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
